### ISSUE TITLE
AttributeError: module '_ACTIONet' has no attribute 'build_ACTIONet'

### ISSUE THREAD

**Issue by pchiang5** [shmohammadi86/ACTIONet#25]
Hello,

I tried the following codes:

```
adata.var_names_make_unique(join='.')
an.pp.filter_adata(adata, min_cells_per_feature=0.01, min_features_per_cell=500) 
sc.pp.normalize_total(adata)
sc.pp.log1p(adata)

an.pp.reduce_kernel(adata)
an.run_ACTIONet(adata)
```
Everything was fine until I got the error below. How could I fix the error?  Thank you.

> Running ACTION (22 threads):
>         Iterating from k = 2 ... 30: 29/29 finished
> Joining trace of C & H matrices (depth = 30) ... done (464 archetypes)
> Pruning archetypes:
>         Non-specific archetypes: 3
>         Unreliable archetypes: 26
>         Trivial archetypes: 40
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/root/miniconda3/envs/actionet/lib/python3.8/site-packages/ACTIONet/main.py", line 74, in run_ACTIONet
>     nt.build_network(
>   File "/root/miniconda3/envs/actionet/lib/python3.8/site-packages/ACTIONet/network/build.py", line 59, in build_network
>     G = _an.build_ACTIONet(H_stacked=H_stacked,
> AttributeError: module '_ACTIONet' has no attribute 'build_ACTIONet'

**Comment by sebastianpineda** [comment]
Hi, the python version is still in development. The issue you noted here was fixed a few days ago, but the pipeline still won't run in it's entirety. I hope to have at least the core functions working in a few days. If you don't mind using R, the release branch for that (and maybe the dev) is stable.
